import{a as y,S as b,i}from"./assets/vendor-DOgVoBmD.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const g of r.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&o(g)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const h=t=>`
    <li class="gallery-card">
       <a href="${t.largeImageURL}" title="${t.tags}">
           <img class="gallery-img" src="${t.webformatURL}" alt="${t.tags}" />
       </a>
       <ul class="stat-img">
           <li class="img-stat-item">Likes <span class="number-of-stat">${t.likes}</span></li>
           <li class="img-stat-item">Views <span class="number-of-stat">${t.views}</span></li>
           <li class="img-stat-item">Comments <span class="number-of-stat">${t.comments}</span></li>
           <li class="img-stat-item">Downloads <span class="number-of-stat">${t.downloads}</span></li>
       </ul>
    </li>
    `,L="https://pixabay.com/api/",f=async(t,s)=>{try{const a={params:{q:t,orientation:"horizontal",page:s,per_page:15,key:"45497630-f588d73f1b1f7379927f92167"}};return await y.get(`${L}`,a)}catch{iziToast.show({message:"An error occurred while fetching images. Please try again.",backgroundColor:"#ef4040",messageColor:"#fafafb",messageSize:"16px",messageLineHeight:"150%",maxWidth:432,position:"topRight",iconUrl:"./img/icon-error.svg"})}};let d,l=1,n="";const p=document.querySelector(".form"),w=document.querySelector('input[type="text"]'),c=document.querySelector(".ul-gallery"),u=document.querySelector(".loader-container"),m=document.querySelector(".load-more-button"),v=async t=>{try{t.preventDefault(),n=p.elements.user_value.value.trim();const s=await f(n,l);if(l=1,n===""){i.show({message:"Error! Please enter a search term!",backgroundColor:"#ef4040",messageColor:"#fafafb",messageSize:"16px",messageLineHeight:"150%",maxWidth:432,position:"topRight",iconUrl:"./img/icon-error.svg"});return}if(s.data.hits.length===0){i.show({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#ef4040",messageColor:"#fafafb",messageSize:"16px",messageLineHeight:"150%",maxWidth:432,position:"topRight",iconUrl:"./img/icon-error.svg"});return}w.value="";const a=s.data.hits.map(o=>h(o)).join("");c.innerHTML=a,d.refresh(),u.classList.add("is-hidden"),m.classList.remove("is-hidden"),c.children.length>=s.data.totalHits&&(m.classList.add("is-hidden"),i.show({message:"We're sorry, but you've reached the end of search results.",backgroundColor:" #4e75ff",messageColor:"#fafafb",messageSize:"16px",messageLineHeight:"150%",maxWidth:432,position:"topRight"}))}catch(s){i.show({message:"An error occurred while fetching images. Please try again.",backgroundColor:"#ef4040",messageColor:"#fafafb",messageSize:"16px",messageLineHeight:"150%",maxWidth:432,position:"topRight",iconUrl:"./img/icon-error.svg"}),u.classList.add("is-hidden"),console.log(s)}};document.addEventListener("DOMContentLoaded",function(){d=new b(".ul-gallery a",{captions:!0,captionDelay:250,animationSpeed:300,captionsData:"title"})});const x=async t=>{try{l++;const a=(await f(n,l)).data.hits.map(e=>h(e)).join("");c.insertAdjacentHTML("beforeend",a),d.refresh();const o=c.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:o*3,behavior:"smooth"})}catch{i.show({message:"An error occurred while fetching images. Please try again.",backgroundColor:"#ef4040",messageColor:"#fafafb",messageSize:"16px",messageLineHeight:"150%",maxWidth:432,position:"topRight",iconUrl:"./img/icon-error.svg"})}};p.addEventListener("submit",v);m.addEventListener("click",x);
//# sourceMappingURL=index.js.map
