import{a as y,S as b,i}from"./assets/vendor-DOgVoBmD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const h=s=>`
    <li class="gallery-card">
       <a href="${s.largeImageURL}" title="${s.tags}">
           <img class="gallery-img" src="${s.webformatURL}" alt="${s.tags}" />
       </a>
       <ul class="stat-img">
           <li class="img-stat-item">Likes <span class="number-of-stat">${s.likes}</span></li>
           <li class="img-stat-item">Views <span class="number-of-stat">${s.views}</span></li>
           <li class="img-stat-item">Comments <span class="number-of-stat">${s.comments}</span></li>
           <li class="img-stat-item">Downloads <span class="number-of-stat">${s.downloads}</span></li>
       </ul>
    </li>
    `,L="https://pixabay.com/api/",f=(s,t)=>{const o={params:{q:s,orientation:"horizontal",page:t,per_page:15,key:"45497630-f588d73f1b1f7379927f92167"}};return y.get(`${L}`,o)};let m,d=1,n="";const p=document.querySelector(".form"),v=document.querySelector('input[type="text"]'),l=document.querySelector(".ul-gallery"),g=document.querySelector(".loader-container"),u=document.querySelector(".load-more-button"),w=async s=>{try{s.preventDefault(),n=p.elements.user_value.value.trim();const t=await f(n,d);if(n===""){i.show({message:"Error! Please enter a search term!",backgroundColor:"#ef4040",messageColor:"#fafafb",messageSize:"16px",messageLineHeight:"150%",maxWidth:432,position:"topRight",iconUrl:"./img/icon-error.svg"});return}if(t.data.hits.length===0){i.show({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#ef4040",messageColor:"#fafafb",messageSize:"16px",messageLineHeight:"150%",maxWidth:432,position:"topRight",iconUrl:"./img/icon-error.svg"});return}v.value="";const o=t.data.hits.map(a=>h(a)).join("");l.innerHTML=o,m.refresh(),g.classList.add("is-hidden"),u.classList.remove("is-hidden")}catch(t){i.show({message:"An error occurred while fetching images. Please try again.",backgroundColor:"#ef4040",messageColor:"#fafafb",messageSize:"16px",messageLineHeight:"150%",maxWidth:432,position:"topRight",iconUrl:"./img/icon-error.svg"}),g.classList.add("is-hidden"),console.log(t)}};document.addEventListener("DOMContentLoaded",function(){m=new b(".ul-gallery a",{captions:!0,captionDelay:250,animationSpeed:300,captionsData:"title"})});const S=async s=>{try{d++;const t=await f(n,d),o=t.data.hits.map(e=>h(e)).join("");l.insertAdjacentHTML("beforeend",o),m.refresh();const a=l.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:a*3,behavior:"smooth"}),l.children.length===t.data.totalHits&&(u.classList.add("is-hidden"),i.show({message:"We're sorry, but you've reached the end of search results.",backgroundColor:" #4e75ff",messageColor:"#fafafb",messageSize:"16px",messageLineHeight:"150%",maxWidth:432,position:"topRight"})),console.log(t)}catch(t){console.log(t)}};p.addEventListener("submit",w);u.addEventListener("click",S);
//# sourceMappingURL=index.js.map
